### ISSUE TITLE
No Project Structure :sad:

### ISSUE THREAD

**Issue by biodunch** [Ayomiga/PhpLearnOnTheJob#2]
You forgot the integral part a starting a `project`. Check out how to properly structure a` web project`, you can't just pack db queries and server script together, assets, etc. 

Happy Learning, Bruvv!

**Comment by Hybeecodes** [comment]
Actually, he just started php.  So, he needs to understand few things before abstracting.

**Comment by biodunch** [comment]
Oh of course I know,,,

That's not abstraction bros.... It's called proper organisation and it's a fundamental concept. Good one anyways, but I expect his next commit to come with the proper structuring. 

below are links to some pointers:
https://dzone.com/articles/how-to-properly-structure-your-php-projects
https://www.quora.com/How-do-I-structure-a-big-PHP-project

:grin:

**Comment by Ayomi-kun** [comment]
structuring of what exactly, this is a scratch pad like project.

it is not a project in its entirety, it just has different modules to help the understand the body well. I even did a checkbox in the read me for the different modules i would be touching

**Comment by Ayomi-kun** [comment]
Have i attended to your issues Biodun Chris? if so you can leave this issue thread closed.
